export const VALID_SALARY_HEADERS = [
  "ID",
  "Name",
  "Annual CTC",
  "Basic Salary",
  "HRA",
  "LTA",
  "Other Allowances",
  "Incentives",
  "Overtime",
  "Statutory Bonus",
  "Bonus",
  "Advance Recovery",
  "Employee PF",
  "Employer PF",
  "ESIC",
  "Gratuity",
  "Professional Tax",
  "TDS",
  "Insurance",
  "LOP Days",
  "LOP Deduction",
  "Gross Salary",
  "Net Salary",
];
