export const MAX_DOWNLOAD_FIELDS = 13;
export const PREVIEW_PAGE_SIZE = 10;
export const MAX_RANGE_DAYS = 62;

export const STATUS_OPTIONS = {
  leaves: ["All", "Pending", "Approved", "Rejected"],
  reimbursements: [
    "All",
    "Pending",
    "Approved",
    "Rejected",
    "Approved/Pending",
    "Approved/paid",
  ],
  employees: ["All", "Active", "Inactive"],
  assets: [
    "All",
    "Pending",
    "In Use",
    "Assigned",
    "Returned",
    "Decommissioned",
  ],
  attendance: ["All", "Punch In", "Punch Out"],
  tasks_supervisor: [
    "All",
    "Completed",
    "Yet to Start",
    "In Progress",
    "On Hold",
  ],
  tasks_employee: ["All", "Completed", "Add on", "Re work", "Incomplete"],
};

export const SUB_OPTIONS = {
  leaves: [
    { key: "leave_id", label: "Leave ID" },
    { key: "employee_id", label: "Employee ID" },
    { key: "employee_name", label: "Employee Name" },
    { key: "department_name", label: "Department" },
    { key: "leave_type", label: "Leave Type" },
    { key: "start_date", label: "Start Date" },
    { key: "end_date", label: "End Date" },
    { key: "status", label: "Status" },
    { key: "reason", label: "Reason" },
    { key: "H_F_day", label: "Half/Full Day" },
    { key: "compensated_days", label: "Compensated Days" },
    { key: "deducted_days", label: "Deducted Days" },
    { key: "loss_of_pay_days", label: "LOP" },
    { key: "preserved_leave_days", label: "Preserved Leaves" },
    { key: "comments", label: "Comments" },
    { key: "created_at", label: "Created At" },
    { key: "updated_at", label: "Updated At" },
  ],
  reimbursements: [
    { key: "id", label: "Reimbursement ID" },
    { key: "employee_id", label: "Employee ID" },
    { key: "employee_name", label: "Employee Name" },
    { key: "department_name", label: "Department" },

    { key: "claim_type", label: "Title" },
    { key: "date", label: "Date" },
    { key: "total_amount", label: "Total Amount" },
    { key: "approval_status", label: "Approval Status" },
    { key: "approver_comments", label: "Approver Comment" },
    { key: "approver_name", label: "Approver Name" },
    { key: "payment_status", label: "Payment Status" },
    { key: "created_at", label: "Created At" },
  ],
  employees: [
    { key: "employee_id", label: "Employee ID" },
    { key: "name", label: "Name" },
    { key: "first_name", label: "First Name" },
    { key: "last_name", label: "Last Name" },
    { key: "email", label: "Email" },
    { key: "phone_number", label: "Phone" },
    { key: "status", label: "Status" },
    { key: "department_name", label: "Department" },
    { key: "role", label: "Role" },
    { key: "position", label: "Position" },
    { key: "joining_date", label: "Joining Date" },
    { key: "dob", label: "DOB" },
    { key: "created_at", label: "Created At" },
  ],
  vendors: [
    { key: "vendor_id", label: "vendor_id" },
    { key: "company_name", label: "company_name" },
    { key: "registered_address", label: "registered_address" },
    { key: "city", label: "city" },
    { key: "gst_number", label: "gst_number" },
    { key: "pan_number", label: "pan_number" },
    { key: "company_type", label: "company_type" },
    { key: "contact1_mobile", label: "contact_mobile" },
    { key: "contact1_email", label: "contact_email" },
    { key: "bank_name", label: "bank_name" },
    { key: "account_number", label: "account_number" },
    { key: "product_category", label: "product_category" },
    { key: "created_at", label: "created_at" },
  ],
  assets: [
    { key: "asset_id", label: "asset_id" },
    { key: "asset_code", label: "asset_code" },
    { key: "asset_name", label: "asset_name" },
    { key: "configuration", label: "configuration" },
    { key: "category", label: "category" },
    { key: "sub_category", label: "sub_category" },
    { key: "assigned_to", label: "assigned_to" },
    { key: "valuation_date", label: "valuation_date" },
    { key: "status", label: "status" },
    { key: "count", label: "count" },
    { key: "created_at", label: "created_at" },
  ],
  attendance: [
    { key: "punch_id", label: "Punch ID" },
    { key: "employee_id", label: "Employee ID" },
    { key: "punch_status", label: "Status" },
    { key: "punchin_time", label: "Punch In Time" },
    { key: "punchin_device", label: "Punch In Device" },
    { key: "punchin_location", label: "Punch In Location" },
    { key: "punchout_time", label: "Punch Out Time" },
    { key: "punchout_device", label: "Punch Out Device" },
    { key: "punchout_location", label: "Punch Out Location" },
    { key: "punchmode", label: "Punch Mode" },
  ],
  tasks_supervisor: [
    { key: "task_id", label: "Task ID" },
    { key: "employee_id", label: "Employee ID" },
    { key: "employee_name", label: "Employee Name" },
    { key: "task_title", label: "Task Title" },
    { key: "description", label: "Description" },
    { key: "start_date", label: "Start Date" },
    { key: "due_date", label: "Due Date" },
    { key: "status", label: "Status" },
    { key: "percentage", label: "% Complete" },
    { key: "progress_percentage", label: "Progress %" },
    { key: "created_at", label: "Created At" },
    { key: "updated_at", label: "Updated At" },
  ],
  tasks_employee: [
    { key: "week_id", label: "Week ID" },
    { key: "task_date", label: "Task Date" },
    { key: "project_id", label: "Project ID" },
    { key: "project_name", label: "Project Name" },
    { key: "task_id", label: "Task ID" },
    { key: "task_name", label: "Weekly Task Name" },
    { key: "replacement_task", label: "Replacement Task" },
    { key: "employee_id", label: "Employee ID" },
    { key: "employee_name", label: "Employee Name" },
    { key: "emp_status", label: "Employee Status" },
    { key: "emp_comment", label: "Employee Comment" },
    { key: "sup_status", label: "Supervisor Status" },
    { key: "sup_comment", label: "Supervisor Comment" },
    { key: "sup_review_status", label: "Supervisor Review Status" },
    { key: "star_rating", label: "Star Rating" },
    { key: "parent_task_id", label: "Parent Task ID" },
    { key: "created_at", label: "Created At" },
    { key: "updated_at", label: "Updated At" },
  ],
};
